# Generated by Django 2.0.3 on 2018-09-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_terminal', models.CharField(max_length=50)),
                ('land_terminal', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('land_time', models.DateTimeField(verbose_name='Land Time')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=670)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('places', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(default=1)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Samoloty.Flight')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Samoloty.Passenger')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together={('name', 'surname')},
        ),
        migrations.AddField(
            model_name='flight',
            name='plane_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Samoloty.Plane'),
        ),
    ]
