# Generated by Django 2.0.3 on 2018-09-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Samoloty', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('owner', 'flight_id')},
        ),
    ]
